# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: usarral
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Madrid
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_repositories: 100
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          plugin_repositories_featured: LyricalString/Node-Discord-Bot
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://usarral.me
          plugin_wakatime_user: usarral
